//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package engine;

import engine.instruction.SInstruction;
import engine.instruction.SInstructionAdapter;
import jakarta.xml.bind.annotation.*;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{}S-Instruction" maxOccurs="unbounded"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sInstruction"
})
@XmlRootElement(name = "S-Instructions")
public class SInstructions implements Serializable {

    @XmlElement(name = "S-Instruction", required = true)
    @XmlJavaTypeAdapter(SInstructionAdapter.class)
    private List<SInstruction> sInstruction;

    public SInstructions() {
        this.sInstruction = new ArrayList<>();
    }

    public SInstructions(List<SInstruction> sInstruction) {
        this.sInstruction = sInstruction;
    }

    private void updateInstructionsLines(){
        for(int i = 0; i < sInstruction.size(); i++){
            sInstruction.get(i).setLine(i+1);
        }
    }

    public List<SInstruction> getSInstruction() {
        updateInstructionsLines();
        return this.sInstruction;
    }

}
