//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package engine.functions;

import engine.SInstructions;
import engine.SInstructionsView;
import engine.SProgramView;
import jakarta.xml.bind.annotation.*;

import java.io.Serializable;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sInstructions"
})
@XmlRootElement(name = "S-Function")
public class SFunction implements Serializable, SProgramView {

    @XmlElement(name = "S-Instructions", required = true)
    protected SInstructions sInstructions;
    @XmlAttribute(name = "user-string", required = true)
    protected String userString;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    @XmlTransient
    protected String uploader = "";
    @XmlTransient
    protected int num_runs = 0;
    @XmlTransient
    protected String parentProgram = "";
    @XmlTransient
    protected int average_credits_cost = 0;

    public SInstructions getSInstructions() {
        sInstructions.updateInstructionsLines();
        return sInstructions;
    }

    public void setSInstructions(SInstructions value) {
        this.sInstructions = value;
    }

    @Override
    public String getUserString() {
        return userString;
    }

    public void setUserString(String value) {
        this.userString = value;
    }

    public String getName() {
        return name;
    }

    @Override
    public SInstructionsView getInstructionsView() {
        sInstructions.updateInstructionsLines();
        return sInstructions;
    }

    public void setName(String value) {
        this.name = value;
    }


    @Override
    public ProgramType getProgramType() {
        return ProgramType.FUNCTION;
    }
    @Override
    public String getUploader() {
        return uploader;
    }
    @Override
    public void setUploader(String value) {
        this.uploader = value;
    }
    @Override
    public int getNumRuns() {
        return num_runs;
    }
    @Override
    public void setNumRuns(int value) {
        this.num_runs = value;
    }
    @Override
    public void addNumRuns(int value) {
        this.num_runs += value;
    }
    @Override
    public int getAverage_credits_cost() {
        return this.average_credits_cost;
    }
    @Override
    public void setAverage_credits_cost(int value) {
        this.average_credits_cost = value;
    }

    @Override
    public String getParentProgram() {
        return parentProgram;
    }
    public void setParentProgram(String value) {
        this.parentProgram = value;
    }
}
