//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package engine.functions;

import engine.SInstructionsView;
import engine.SProgramView;
import engine.SInstructions;
import engine.instruction.SInstruction;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;

import java.io.Serializable;
import java.util.List;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sInstructions"
})
@XmlRootElement(name = "S-Function")
public class SFunction implements Serializable, SProgramView {

    @XmlElement(name = "S-Instructions", required = true)
    protected SInstructions sInstructions;
    @XmlAttribute(name = "user-string", required = true)
    protected String userString;
    @XmlAttribute(name = "name", required = true)
    protected String name;


    public SInstructions getSInstructions() {
        sInstructions.updateInstructionsLines();
        return sInstructions;
    }

    public void setSInstructions(SInstructions value) {
        this.sInstructions = value;
    }

    @Override
    public String getUserString() {
        return userString;
    }

    public void setUserString(String value) {
        this.userString = value;
    }

    public String getName() {
        return name;
    }

    @Override
    public SInstructionsView getInstructionsView() {
        sInstructions.updateInstructionsLines();
        return sInstructions;
    }

    public void setName(String value) {
        this.name = value;
    }

    @Override
    public ProgramType getProgramType() {
        return ProgramType.FUNCTION;
    }
}
